name: "Enforce Branch PR's from Develop"

# This reusable workflow enforces that PRs to main branch only come from develop or hotfix branches
# It helps maintain a clean Git workflow and prevents direct commits to main

on:
  workflow_call:
    secrets:
      lerian_studio_push_bot_app_id:
        required: true
      lerian_studio_push_bot_private_key:
        required: true
      lerian_ci_cd_user_gpg_key:
        required: true
      lerian_ci_cd_user_gpg_key_password:
        required: true
      lerian_ci_cd_user_name:
        required: true
      lerian_ci_cd_user_email:
        required: true

jobs:
  check-branch:
    runs-on: ubuntu-24.04
    steps:
      # Generate GitHub App token for authentication
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.lerian_studio_push_bot_app_id }}
          private-key: ${{ secrets.lerian_studio_push_bot_private_key }}

      # Import GPG key for signing commits
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.lerian_ci_cd_user_gpg_key }}
          passphrase: ${{ secrets.lerian_ci_cd_user_gpg_key_password }}
          git_committer_name: ${{ secrets.lerian_ci_cd_user_name }}
          git_committer_email: ${{ secrets.lerian_ci_cd_user_email }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      # Check if PR is from develop or hotfix branch
      - name: Check if PR is from develop or hotfix
        if: github.event.pull_request.head.ref != 'develop' && startsWith(github.event.pull_request.head.ref, 'hotfix/') == false
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_AUTHOR_NAME: ${{ secrets.lerian_ci_cd_user_name }}
          GIT_AUTHOR_EMAIL: ${{ secrets.lerian_ci_cd_user_email }}
          GIT_COMMITTER_NAME: ${{ secrets.lerian_ci_cd_user_name }}
          GIT_COMMITTER_EMAIL: ${{ secrets.lerian_ci_cd_user_email }}
        run: |
          echo "Pull requests to main can only come from develop or hotfix branches."
          # Add a request for changes comment on the pull request
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"body": "Pull requests to **main** can only come from **develop** or **hotfix** branches. Please **change base**!!!", "event": "REQUEST_CHANGES"}' \
            "${{ github.event.pull_request.url }}/reviews"
          exit 1
